#!/usr/bin/env python3
"""Build viewer/data.js from all *.md files under agentic2/ (excluding viewer/).

Docs are emitted in fixed reading order:
  README -> 00_day_plan -> 01_core/* -> 02_playbook -> 03_gaps/* ->
  04_benchmarks -> 05_questions/* -> 06_company_briefs -> 07_labs_guide -> 08_cheatsheet

Output: window.A2_DOCS = [{path, group, title, content}]
Run:    python3 build_data.py   (idempotent; rerun after content changes)
"""
import json
import os
import re
import sys

VIEWER_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(VIEWER_DIR)
OUT = os.path.join(VIEWER_DIR, "data.js")

# Reading order: prefix of path relative to ROOT ("README.md" matches exactly).
ORDER = [
    "README.md",
    "00_day_plan",
    "01_core",
    "02_playbook",
    "03_gaps",
    "04_benchmarks",
    "05_questions",
    "06_company_briefs",
    "07_labs_guide",
    "08_cheatsheet",
]

EXCLUDE_DIRS = {"viewer", ".git", "node_modules", "__pycache__"}


def discover():
    files = []
    for dirpath, dirnames, filenames in os.walk(ROOT):
        dirnames[:] = [d for d in dirnames if d not in EXCLUDE_DIRS]
        for fn in filenames:
            if fn.lower().endswith(".md"):
                full = os.path.join(dirpath, fn)
                rel = os.path.relpath(full, ROOT).replace(os.sep, "/")
                files.append(rel)
    return files


def order_key(rel):
    group_idx = len(ORDER)  # unknown groups go last
    for i, prefix in enumerate(ORDER):
        if rel == prefix or rel.startswith(prefix + "/") or rel.startswith(prefix + "."):
            group_idx = i
            break
    # within a group: README first, then alphabetical
    base = rel.rsplit("/", 1)[-1]
    readme_first = 0 if base.lower() == "readme.md" and "/" in rel else 1
    return (group_idx, readme_first, rel.lower())


def group_of(rel):
    for prefix in ORDER:
        if rel == prefix or rel.startswith(prefix + "/") or rel.startswith(prefix + "."):
            return prefix.replace(".md", "")
    return "other"


def title_of(rel, text):
    for line in text.splitlines():
        m = re.match(r"^#\s+(.+?)\s*$", line.strip())
        if m:
            return m.group(1)
    return rel.rsplit("/", 1)[-1].replace(".md", "")


def main():
    docs = []
    for rel in sorted(discover(), key=order_key):
        full = os.path.join(ROOT, rel)
        try:
            with open(full, encoding="utf-8") as f:
                text = f.read()
        except UnicodeDecodeError:
            with open(full, encoding="utf-8", errors="replace") as f:
                text = f.read()
        docs.append({
            "path": rel,
            "group": group_of(rel),
            "title": title_of(rel, text),
            "content": text,
        })

    payload = json.dumps(docs, ensure_ascii=False, indent=1)
    # script-safety: never allow "</script" or JS line separators inside the literal
    payload = payload.replace("</", "<\\/")
    payload = payload.replace("\u2028", "\\u2028").replace("\u2029", "\\u2029")

    with open(OUT, "w", encoding="utf-8") as f:
        f.write("// generated by build_data.py -- do not edit\n")
        f.write("window.A2_DOCS = " + payload + ";\n")

    print(f"wrote {OUT}: {len(docs)} docs")
    for d in docs:
        print(f"  [{d['group']}] {d['path']} -> {d['title']}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
